### ISSUE TITLE
Can't find map file if it's included inside of a DM file

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#214]
NTstation uses code files (`.dm`) for map inclusion shenanigans. OpenDream treats this as no map included because it's not in the DME, presumably.

**Comment by wixoaGit** [comment]
A map can be included from anywhere. The problem is the map is being included with a relative path, instead of its full path. (Seen [here](https://github.com/ike709/NTstation13/blob/master/_maps/metastation.dm#L3), `"map_files\MetaStation.v39L.dmm"` instead of `"_maps\map_files\MetaStation.v39L.dmm"`)

**Comment by wixoaGit** [comment]
This shouldn't be an issue anymore.
