### ISSUE TITLE
[Robust] Clicking is broken

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#370]

**Comment by ike709** [comment]
Is this fixed by https://github.com/wixoaGit/OpenDream/commit/5e41d12409a0b051928777227ca56d457dbf2573 ?

**Comment by wixoaGit** [comment]
> 
> 
> Is this fixed by [5e41d12](https://github.com/wixoaGit/OpenDream/commit/5e41d12409a0b051928777227ca56d457dbf2573) ?

No. Clicking itself is not broken, `Click()` is currently called whenever you click an atom. The real issue is that none of the click parameters are passed to the proc at the moment (`icon-x`, `shift`, `ctrl`, etc). SS13 codebases do not like this.

https://github.com/wixoaGit/OpenDream/blob/RobustToolbox/OpenDreamRuntime/Input/MouseInputSystem.cs#L37
`//TODO: click params ("icon-x", "icon-y", "screen-loc", "shift", "ctrl", "alt")`

**Comment by wixoaGit** [comment]
> The real issue is that none of the click parameters are passed to the proc at the moment


A quick look revealed that this was not the real reason that clicking wasn't working in ss13 codebases. `usr` was null when calling `/client.Click()`, leading to an exception when attempting to call a proc on it. This was fixed in 0b79bf13b715772b04c71728dc7a2249bc2e7cc0.
