### ISSUE TITLE
`new /list()` doesn't work

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#477]
```
var/list/thing = new /list(2)

world.log << length(thing)
```
Expected: 2
Actual: 0

**Comment by wixoaGit** [comment]
The problem is caused by [this line](https://github.com/wixoaGit/OpenDream/blob/ba34c3d43e7865271248afd9bdd241d4d452a555/OpenDreamShared/Dream/DreamPath.cs#L124). `length()` determines if the argument is a list by doing `value.TryGetValueAsDreamObjectOfType(DreamPath.List, out DreamObject listObject)` which is ultimately calling `DreamPath.List.IsDescendantOf(DreamPath.List)`. This returns false, leading `TryGetValueAsDreamObjectOfType` to fail.

**Comment by ike709** [comment]
Can't you just remove the return immediately after that: https://github.com/wixoaGit/OpenDream/blob/ba34c3d43e7865271248afd9bdd241d4d452a555/OpenDreamShared/Dream/DreamPath.cs#L125 ?

**Comment by wixoaGit** [comment]
After some light testing, that appears to work. In the future I'd like a rework of how list vars work to more correctly match their behavior in DM/BYOND.

c3ef1059a65d52ff78b0b231a8adf9931ad5fec6
