### ISSUE TITLE
Switch() block if() statements error, expecting a constant

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#699]
The switch() block if() statement arguments below generate the error `Expected a constant` in the lines marked with `[*]`
```
switch(health)
[*]	if(max_health*0.5 to max_health)
		to_chat(user, "<span class='notice'>It appears slightly dented.</span>")
	if(1 to max_health*0.5)
		to_chat(user, "<span class='warning'>It appears heavily dented.</span>")
	if((INFINITY * -1) to 0)
		to_chat(user, "<span class='danger'>It appears completely unsalvageable.</span>")
```

and 

```
switch(amount)
	if(0)
		icon_state = "linenbin-empty"
[*]	if(1 to amount / 2)
		icon_state = "linenbin-half"
	else				icon_state = "linenbin-full"
```

**Comment by wixoaGit** [comment]
This is actually a bug we discovered in the byond compiler some months ago. Switch cases should only ever use constants, but it for some reason they allow a non-constant inside `a to b` cases. While it will compile, the non-constant is incorrectly treated as `null`.

This bug was reported but hasn't yet gotten a response. http://www.byond.com/forum/post/2750423

**Comment by Hinaichigo** [comment]
Oh, I see.
