### ISSUE TITLE
Local object vars inaccessible in static var declaration

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#734]
When attempting to compile /vg/station, the following error occurs:
`Error at code\game\machinery\atmoalter\canister.dm:128:14: Unknown identifier "icon"`
at the following location:
```
126 /obj/machinery/portable_atmospherics/canister/proc/pressure_overlays(var/state)
127 	var/static/list/status_overlays_pressure = list(
128 		image(icon, "can-o0"),
129 		image(icon, "can-o1"),
130 		image(icon, "can-o2"),
131 		image(icon, "can-o3")
132 	)
133 
134 	return status_overlays_pressure[state]
```
It seems that it doesn't recognize it's own `icon` as a var, or else it's conflicting with the fact that the first arg of `image()` is also called `icon`, or something.

**Comment by wixoaGit** [comment]
This is because `status_overlays_pressure` is a static var, while `icon` is not. In BYOND this will actually treat `icon` as null, so this will do `image(null, "can-o0")` instead of using `icon` as you might expect.

This doesn't lead to visibly incorrect behavior in this case because an overlay will use the atom's current icon if the image doesn't have its own.

**Comment by Hinaichigo** [comment]
Is it correct to say that `static` is functionally identical to `global`?
If so, the issue here would be that it's trying to reference `icon` but icon doesn't exist on a global scope, and is only defined for specific objects, and a global var definition only has access to other global vars and global procs?

**Comment by wixoaGit** [comment]
Yes, that's exactly it.

**Comment by Hinaichigo** [comment]
I see. Since it's an issue with BYOND I'll close this.

**Comment by Hinaichigo** [comment]
I think this might be different than we thought actually.
It seems like in BYOND, "global variables" (declared using `/var Var = 1`) are actually distinct from `var/global` aka `var/static`.
Here's some information and:
http://www.byond.com/forum/post/2140538
this is what led me to realize it might otherwise:
https://github.com/vgstation-coders/vgstation13/pull/32807

Maybe this is the root of the static vars issue.

**Comment by Exxion** [comment]
Further testing shows that you are correct and this is the same behavior as in BYOND, *but* that behavior in BYOND causes additional even weirder behavior and is almost certainly not how it's *supposed* to work.

**Comment by wixoaGit** [comment]
So if I'm understanding this correctly, the BYOND compiler is seeing the local var `icon` on the object the proc belongs to, and so doesn't error on it despite this being a global variable. During global initialization at runtime it tries to access `world.icon`, and because of special `world` behavior it doesn't runtime and instead results in null?

If so, it seems OpenDream is doing the more "correct" behavior here and isn't recognizing `icon` as a usable var in the first place.

**Comment by Exxion** [comment]
Yes, pretty much. It might be helpful to have the error message give more information in the specific case of accesses in static var initialization, but if that's not simple to implement it seems fine as-is.
